[mysql]
host = "localhost"
port = 3306
database = "global_seismic_trends"
user = "root"
password = "12345678"

[railway]
host = "altaria.proxy.rlwy.net"
port = 51770
database = "railway"
user = "root"
password = "tVvNpvplhWncFnKojCvqgZwNCbhLvzHI"
MYSQL_HOST = "altaria.proxy.rlwy.net"
MYSQL_PORT = 51770
MYSQL_DATABASE = "railway"
MYSQL_USER = "root"
MYSQL_PASSWORD = "tVvNpvplhWncFnKojCvqgZwNCbhLvzHI"